### ISSUE TITLE
Input Classes missing for Form component > Simple Stacked Component

### ISSUE THREAD

**Issue by rbazzle** [tailwindlabs/tailwindui-issues#348]
**What component (if applicable)**
https://tailwindui.com/components/application-ui/forms/form-layouts

- Component name: 
Form Layouts > Simple Stacked

**Describe the bug**
The preview appears to be correct, but the code snippet seems wrong.
The classes for some of the input fields are as follows:
`class="form-input block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5"`

**Expected behavior**
In following patterns consistent with other components, the code should likely be:
`class="mt-1 form-input block w-full py-2 px-3 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:shadow-outline-blue focus:border-blue-300 transition duration-150 ease-in-out sm:text-sm sm:leading-5"`

**Comment by simonswiss** [comment]
Hey!

Thanks for flagging that 👍

Acutally, I think we need to do the opposite: the following classes...

```py-2 px-3 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:shadow-outline-blue focus:border-blue-300``` 

...are extraneous where used in conjunction with `form-input`, since the `form-input` class takes care of these styles by itself:

```css
.form-input {
    appearance: none;
    background-color: #fff;
    border-color: #d2d6dc;
    border-width: 1px;
    border-radius: .375rem;
    padding: .5rem .75rem;
    font-size: 1rem;
    line-height: 1.5
}

.form-input:focus {
    outline: none;
    box-shadow: 0 0 0 3px rgba(164,202,254,.45);
    border-color: #a4cafe
}
```

So the fix here would be to remove these classes in the examples that use them 👍

Thanks again for bringing this to our attention! 👍
