### ISSUE TITLE
Date Pickers

### ISSUE THREAD

**Issue by HeinHanekom** [tailwindlabs/tailwindui-issues#54]
Date pickers & the variants that come with it is something that we use in very single application & it is insanely hard to style them if you are not a CSS/Tailwind wizzard like you guys. :-)

Would be really awesome to examples of all the basic date picker options such as:

- Single Date Picker
- Date Range Picker
- Date & Time Pickers
- Date Range Picker With Pre Selection panel (Last Month, Last 3 Months etc)

I think Elements has done an amazing job and it's what we've been using so far but Elements is a massive UI library to pull in just to have nice looking date pickers.
https://element.eleme.io/#/en-US/component/date-picker#datepicker

We would Love to replace all our bootstrap and elements stuff with TailwindCSS but this is probably the only thing holding us back at the moment.

Here's some really nice looking Dribble Designs for inspiration (Obviously it would be awesome to have these with styling that matches the rest of the Tailwind UI look and feel):
LOVE THIS FIRST ONE
https://dribbble.com/shots/4294398-Dashboard-UX-01-Date-Range-Picker

https://dribbble.com/shots/5256244-Project-management-UI-elements
https://dribbble.com/shots/4597545-Hotelchamp-Datepicker
https://dribbble.com/shots/6941481-Datepicker-Select-Period-Exploration
https://dribbble.com/shots/2140947-jQuery-Date-Range-Picker-V2
https://dribbble.com/shots/5581230-Date-Picker
https://dribbble.com/shots/3083297-Calendar

Thanks Guys! HUGE FAN.

**Comment by dillingham** [comment]
@HeinHanekom your links are broken

**Comment by HeinHanekom** [comment]
Thanks @dillingham . Should be working now. :-)

**Comment by inopinatus** [comment]
I would love to see a TailwindUI date/time picker but let's no underestimate; they are a bottomless pit of complexity, edge cases, wildly varying requirements, and browser special cases.

At this point I'd be happy with guidance as to whether they're even on the roadmap and for which decade.

**Comment by RobinMalfait** [comment]
Also don’t forget that tailwind ui is just the UI part. All the hard complexity will be for you to implement.

**Comment by HeinHanekom** [comment]
Completely understand and have no problem implementing the login ourselves. It's just a matter of having a design that matches the Tailwind UI styles etc. :-) This is just such a crucial element of any large SAAS system that it would be great to have some examples covered as part of this package. Once we have the UI we'll typically build 2 or 3 Vue components from them that we can reuse in all our projects.

**Comment by outlawvik** [comment]
This is the most demanding feature 
Looking forward to see some updates with date-picker

**Comment by inopinatus** [comment]
I'd also settle for about a tutorial in which ~~Bob Ross~~ Adam Wathan deftly produces a series of possible datepickers using TWUI.

**Comment by richardhj** [comment]
This is the CSS I used in combination with https://innologica.github.io/vue2-daterange-picker/. Looks similar like the original picker design but more in line with tailwind UI.

(drafted, may not support all modes)
```scss
.daterangepicker {
  @apply fixed z-30 bg-white overflow-hidden overflow-hidden shadow rounded-lg;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);

  &.show-ranges {
    > .calendars {
      @apply grid grid-cols-4 gap-2;

      > .ranges {
        @apply border-r;
      }

      > .calendars-container {
        @apply col-span-3;
      }
    }
  }

  > .drp-buttons {
    @apply border-t border-gray-200 px-4 py-4 flex justify-end items-center;

    > * {
      @apply ml-3;
    }

    button {
      @apply inline-flex shadow-sm items-center px-2.5 py-1.5 border border-transparent text-xs leading-4 font-medium rounded transition ease-in-out duration-150;

      &.cancelBtn {
        @apply border-gray-300 text-gray-700 bg-white;

        &:hover {
          @apply text-gray-500;
        }

        &:focus {
          @apply outline-none border-gray-700 shadow-outline-blue;
        }
      }

      &.applyBtn {
        @apply text-white bg-primary-600;

        &:hover {
          @apply bg-primary-500;
        }

        &:focus {
          @apply outline-none border-primary-700 shadow-outline-blue;
        }
      }
    }
  }

  .ranges {
    li {
      @apply px-4 py-2 text-sm leading-5 text-gray-700;
      &:hover {
        @apply bg-gray-100 text-gray-900 cursor-pointer;
      }

      &:focus {
        @apply outline-none bg-gray-100 text-gray-900;
      }
    }
  }

  .calendars-container {
    @apply grid grid-cols-2 gap-6 px-4 py-4;
  }

  .calendar-table {
    table {
      @apply w-full;
    }
  }

  .calendar-time {
    @apply flex justify-center items-center pt-2;

    &:before {
      background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none'%3e%3cpath d='M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z' stroke='%239fa6b2' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'/%3e%3c/svg%3e");
      content: '';
      width: 1.25rem;
      height: 1.25rem;
      margin-right: .5rem;
      margin-left: -.5rem;
    }

    select {
      @apply transition duration-150 ease-in-out pl-1 pb-1 pt-1 pr-4 rounded bg-white border outline-none;
      background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 20 20' fill='none'%3e%3cpath d='M7 7l3-3 3 3m0 6l-3 3-3-3' stroke='%239fa6b2' stroke-width='1.5' stroke-linecap='round' stroke-linejoin='round'/%3e%3c/svg%3e");
      -webkit-appearance: none;
      appearance: none;
      color-adjust: exact;
      background-repeat: no-repeat;
      background-position: right 0.125rem center;
      background-size: 1.5em 1.5em;;

      &:focus {
        @apply shadow-outline-blue;
      }

      @screen sm {
        @apply text-sm leading-5;
      }
    }
  }

  td {
    @apply text-xs leading-5 text-gray-900 cursor-pointer px-2 py-1 text-center;

    &.off {
      @apply text-gray-400;
    }

    &.disabled:not(.in-range):hover {
      @apply bg-gray-100 text-gray-700 rounded-full;
    }

    &.in-range {
      @apply bg-blue-100 text-blue-800;
    }

    &.active {
      @apply bg-blue-600 text-white;
    }

    &.start-date {
      @apply rounded-l-md;
    }

    &.end-date {
      @apply rounded-r-md;
    }

    &.week {
      @apply text-gray-300 cursor-auto pointer-events-none;
    }
  }

  th {
    @apply text-sm leading-5 font-medium text-gray-700 py-1;

    &.month {
      @apply font-semibold pointer-events-none;
    }
  }

  tbody th {
    @apply pointer-events-none;
  }

  th.month {
    text-align: center;
  }

  th.prev, th.next {
    content: '';
    background-repeat: no-repeat;
    background-size: 1.25rem;
  }

  th.prev {
    background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none'%3e%3cpath d='M15 19l-7-7 7-7' stroke='%23161e2e' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'/%3e%3c/svg%3e");
    background-position: left;
  }

  th.next {
    background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none'%3e%3cpath d='M9 5l7 7-7 7' stroke='%23161e2e' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'/%3e%3c/svg%3e");
    background-position: right;
  }

  .drp-selected {
    @apply text-xs text-gray-900;
  }
}
```
